# Generated by Django 4.2.11 on 2024-06-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('danceability', models.DecimalField(decimal_places=3, max_digits=5)),
                ('energy', models.DecimalField(decimal_places=3, max_digits=5)),
                ('key', models.IntegerField()),
                ('loudness', models.DecimalField(decimal_places=3, max_digits=6)),
                ('mode', models.IntegerField()),
                ('speechiness', models.DecimalField(decimal_places=3, max_digits=5)),
                ('acousticness', models.DecimalField(decimal_places=3, max_digits=5)),
                ('instrumentalness', models.DecimalField(decimal_places=5, max_digits=8)),
                ('liveness', models.DecimalField(decimal_places=3, max_digits=5)),
                ('valence', models.DecimalField(decimal_places=3, max_digits=5)),
                ('tempo', models.DecimalField(decimal_places=3, max_digits=6)),
                ('time_signature', models.IntegerField()),
            ],
        ),
    ]
