# Generated by Django 4.2.11 on 2024-06-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='danceability',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
