# Generated by Django 4.2.11 on 2024-06-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_tracks_danceability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='acousticness',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='energy',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='instrumentalness',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='liveness',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='loudness',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='speechiness',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='tempo',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='valence',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
